export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// PATIENTS
export const LOAD_PATIENTS = 'LOAD_PATIENTS';
// export const ADD_PATIENT = 'ADD_PATIENT';

//APPOINTMENTS
export const LOAD_APPOINTMENTS = 'LOAD_APPOINTMENTS'

// FOODS
export const LOAD_FOODS = 'LOAD_FOODS';

// RECIPES
export const LOAD_RECIPES = 'LOAD_RECIPES';

// BILLING PLANS
export const LOAD_BILLINGPLANS = 'LOAD_BILLINGPLANS';

// MEAL PLANS
export const LOAD_MEAL_PLANS = 'LOAD_MEAL_PLANS';
export const REMOVE_MEAL_PLAN = 'REMOVE_MEAL_PLAN';

// MEAL PLAN TEMPLATES
export const LOAD_MEAL_PLAN_TEMPLATES = 'LOAD_MEAL_PLAN_TEMPLATES';
export const REMOVE_MEAL_PLAN_TEMPLATE = 'REMOVE_MEAL_PLAN_TEMPLATE';