const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const FoodSchema = new Schema({
  source: String,
  foodId: String,
  isBasicFood: Boolean,
  category: String,
  foodName: String,
  foodName_lowercase: String,
  com_name: String,
  manufac_name: String,
  alcohol_g: Number,
  ash_g: Number,
  caffeine_mg: Number,
  calcium_mg: Number,
  carbs_g: Number,
  carbs_avl_g: Number,
  alpha_carotene_ug: Number,
  beta_carotene_mcg: Number,
  cholesterol_mg: Number,
  choline_mg: Number,
  copper_mg: Number,
  beta_cryptoxanthin_mcg: Number,
  calories_kcal: Number,
  calories_kJ: Number,
  monounsaturated_fat_g: Number,
  polyunsaturated_fat_g: Number,
  saturated_fat_g: Number,
  trans_fat_g: Number,
  fiber_g: Number,
  fluoride_mcg: Number,
  vitaminB9_ug: Number,
  fructose_g: Number,
  galactose_g: Number,
  glucose_g: Number,
  iron_mg: Number,
  lactose_g: Number,
  lutein_zeaxanthin_mcg: Number,
  lycopene_mcg: Number,
  magnesium_mg: Number,
  maltose_g: Number,
  manganese_mg: Number,
  niacin_mg: Number,
  vitaminB5_mg: Number,
  phosphorus_mg: Number,
  potassium_mg: Number,
  protein_g: Number,
  retinol_mcg: Number,
  riboflavin_mg: Number,
  selenium_mcg: Number,
  sodium_mg: Number,
  starch_g: Number,
  sucrose_g: Number,
  sugar_g: Number,
  theobromine_mg: Number,
  thiamin_mg: Number,
  fat_g: Number,
  vitaminA_mcg: Number,
  vitaminB12_: Number,
  vitaminB6_mg: Number,
  vitaminC_mg: Number,
  vitaminD_mcg: Number,
  vitaminD2_mcg: Number,
  vitaminD3_mcg: Number,
  vitaminE_mg: Number,
  water_g: Number,
  zinc_mg: Number,
  weights: {
    Amount0: Number,
    Msre_Desc0: String,
    Gm_Wgt0: Number,
    Amount1: Number,
    Msre_Desc1: String,
    Gm_Wgt1: Number,
    Amount2: Number,
    Msre_Desc2: String,
    Gm_Wgt2: Number,
    Amount3: Number,
    Msre_Desc3: String,
    Gm_Wgt3: Number,
    Amount4: Number,
    Msre_Desc4: String,
    Gm_Wgt4: Number,
    Amount5: Number,
    Msre_Desc5: String,
    Gm_Wgt5: Number,
    Amount6: Number,
    Msre_Desc6: String,
    Gm_Wgt6: Number,
    Amount7: Number,
    Msre_Desc7: String,
    Gm_Wgt7: Number,              
    Amount8: Number,
    Msre_Desc8: String,
    Gm_Wgt8: Number,
    Amount9: Number,
    Msre_Desc9: String,
    Gm_Wgt9: Number,
    Amount10: Number,
    Msre_Desc10: String,
    Gm_Wgt10: Number,
    Amount11: Number,
    Msre_Desc11: String,
    Gm_Wgt11: Number,
    Amount12: Number,
    Msre_Desc12: String,
    Gm_Wgt12: Number,
    Amount13: Number,
    Msre_Desc13: String,
    Gm_Wgt13: Number,
    Amount14: Number,
    Msre_Desc14: String,
    Gm_Wgt14: Number,
    Amount15: Number,
    Msre_Desc15: String,
    Gm_Wgt15: Number,
    Amount16: Number,
    Msre_Desc16: String,
    Gm_Wgt16: Number,
  },
	directions:[{
		type:String
	}],
	ingredients:[{
		type: mongoose.Schema.Types.ObjectId,
		ref: "FoodSchema"
	}]
}, { timestamps: true });

const Food = mongoose.model("Food", FoodSchema);


module.exports = Food;